version: '3.8'

services:
  dispatcher_customer_db:
    image: postgres:12
    container_name: dispatcher_customer_db
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "dispatcher_customer_db"
      PGDATA: "/data/postgres"
    ports:
      - "5436:5436"
    volumes:
      - ./postgres_data:/data/postgres
    command: -p 5436
    restart: on-failure

  customer_dispatcher_api:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
    - "8000:8000"
    volumes:
      - .:/backend
      - ./backend/customer_dispatcher_api/:/code/
    env_file:
      - .env.prod
    restart: always
    depends_on:
      - dispatcher_customer_db