version: '3.8'

services:
  dispatcher_customer_db:
    image: postgres:12
    container_name: dispatcher_customer_db
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "dispatcher_customer_db"
      PGDATA: "/data/postgres"
    ports:
      - "5435:5435"
    volumes:
      - ./postgres_data:/data/postgres
    command: -p 5435
    restart: on-failure

  dispatcher_customer_api:
    build: ./backend
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
    - "8000:8000"
    volumes:
      - .:/backend
      # - ./backend/dispatcher_customer_api/:/code/
    restart: always
    depends_on:
      - dispatcher_customer_db