# Generated by Django 3.2.11 on 2022-10-14 18:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона заказчика')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона заказчика')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип ТС')),
                ('characteristic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Характеристика ТС')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование ТС')),
                ('plate_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер ТС')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус ТС')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.performer', verbose_name='Водитель ТС')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(default=datetime.date(2022, 10, 14), verbose_name='Дата начала брони')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания брони')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус ТС')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='Заказчик')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transport', verbose_name='Забронированный транспорт')),
            ],
        ),
    ]
