# Generated by Django 3.2.11 on 2022-10-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reservation_begin_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='status',
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(blank=True, choices=[('Парк кранов', 'Crane'), ('Парк погрузчиков', 'Lift Truck'), ('Парк автовышек', 'Autotower')], max_length=255, null=True, verbose_name='Тип ТС'),
        ),
    ]
