# Generated by Django 3.2.11 on 2022-10-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='status',
            field=models.CharField(choices=[('FREE', 'Cвободен'), ('IN_WORK', 'В работе'), ('ON_THE_WAY', 'В пути')], default='FREE', max_length=255, verbose_name='Статус ТС'),
        ),
    ]
