# Generated by Django 3.2.11 on 2022-10-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_transport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно ли ТС'),
        ),
    ]
