# Generated by Django 3.2.11 on 2022-10-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transport_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='characteristic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Характеристика ТС'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='type',
            field=models.CharField(blank=True, choices=[('Парк кранов', 'Crane'), ('Парк погрузчиков', 'Lift Truck'), ('Парк автовышек', 'Autotower')], max_length=255, null=True, verbose_name='Тип ТС'),
        ),
    ]
