# Generated by Django 3.2.11 on 2022-10-15 13:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20221015_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='begin_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата начала брони'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('In the search process', 'В процессе поиска'), ('Vehicle found', 'Транспортное средство найдено'), ('Closed', 'Закрыто')], default='In the search process', max_length=255, verbose_name='Статус Брони'),
        ),
    ]
